import type { ConsoleAgent, ConsoleTask, TaskEvent } from "./types";

export const MOCK_AGENTS: ConsoleAgent[] = [
  {
    id: "agent-1",
    name: "报关 Agent",
    icon: "📦",
    sceneId: "M-003",
    sceneName: "进出口报关",
    taskType: "workflow",
    status: "running",
    successRate: 94.2,
    taskCount: 1847,
    avgDuration: "8 分钟",
    version: "v1.3.0",
    department: "外贸部",
    lastActiveAt: "2 分钟前",
    description: "进出口货物的报关单据处理和流程管理",
  },
  {
    id: "agent-2",
    name: "合同审核 Agent",
    icon: "📄",
    sceneId: "M-006",
    sceneName: "合同审批流转",
    taskType: "workflow",
    status: "running",
    successRate: 98.7,
    taskCount: 523,
    avgDuration: "12 分钟",
    version: "v2.1.0",
    department: "法务部",
    lastActiveAt: "15 分钟前",
    description: "合同条款审核、风险标记、审批流转",
  },
  {
    id: "agent-3",
    name: "竞品分析 Agent",
    icon: "📊",
    sceneId: "A-001",
    sceneName: "竞品分析",
    taskType: "agentic",
    status: "running",
    successRate: 96.6,
    taskCount: 89,
    avgDuration: "45 分钟",
    version: "v1.0.2",
    department: "产品部",
    lastActiveAt: "1 小时前",
    description: "对标竞品的产品能力、市场表现进行系统分析",
  },
  {
    id: "agent-4",
    name: "财务报销 Agent",
    icon: "💰",
    sceneId: "M-001",
    sceneName: "财务报销审批",
    taskType: "workflow",
    status: "running",
    successRate: 97.3,
    taskCount: 2104,
    avgDuration: "3 分钟",
    version: "v1.5.0",
    department: "财务部",
    lastActiveAt: "5 分钟前",
    description: "从提交报销到审批完成的全流程自动化",
  },
  {
    id: "agent-5",
    name: "小红书运营 Agent",
    icon: "📱",
    sceneId: "O-001",
    sceneName: "账号运营涨粉",
    taskType: "agentic",
    status: "draft",
    successRate: 0,
    taskCount: 0,
    avgDuration: "-",
    version: "v0.1.0",
    department: "市场部",
    lastActiveAt: "-",
    description: "制定并执行账号运营策略，提升粉丝数和互动率",
  },
];

export const MOCK_TASKS: ConsoleTask[] = [
  {
    id: "T-2850",
    agentId: "agent-1",
    agentName: "报关 Agent",
    agentIcon: "📦",
    currentNode: "海关编码归类",
    progress: 65,
    status: "running",
    startedAt: "2026-04-02 14:20",
    duration: "6 分钟",
    description: "报关单 BG-2026-0392 处理",
  },
  {
    id: "T-2849",
    agentId: "agent-1",
    agentName: "报关 Agent",
    agentIcon: "📦",
    currentNode: "人工确认 · 海关编码",
    progress: 80,
    status: "pending_confirm",
    startedAt: "2026-04-02 13:57",
    duration: "23 分钟",
    priority: "high",
    description: "报关单 BG-2026-0391 处理",
  },
  {
    id: "T-2848",
    agentId: "agent-2",
    agentName: "合同审核 Agent",
    agentIcon: "📄",
    currentNode: "人工确认 · 风险条款",
    progress: 90,
    status: "pending_confirm",
    startedAt: "2026-04-02 13:32",
    duration: "48 分钟",
    priority: "urgent",
    description: "合同 CT-2026-0178 条款审核",
  },
  {
    id: "T-2847",
    agentId: "agent-1",
    agentName: "报关 Agent",
    agentIcon: "📦",
    currentNode: "-",
    progress: 100,
    status: "completed",
    startedAt: "2026-04-02 13:10",
    completedAt: "2026-04-02 13:23",
    duration: "13 分钟",
    description: "报关单 BG-2026-0387 处理",
  },
  {
    id: "T-5012",
    agentId: "agent-3",
    agentName: "竞品分析 Agent",
    agentIcon: "📊",
    currentNode: "数据采集",
    progress: 35,
    status: "running",
    startedAt: "2026-04-02 12:42",
    duration: "1 小时 38 分钟",
    description: "竞品分析 · Q1 市场份额追踪",
  },
  {
    id: "T-6103",
    agentId: "agent-4",
    agentName: "财务报销 Agent",
    agentIcon: "💰",
    currentNode: "-",
    progress: 100,
    status: "completed",
    startedAt: "2026-04-02 14:00",
    completedAt: "2026-04-02 14:02",
    duration: "2 分钟",
    description: "报销单 #6103 · 差旅费 ¥3,200",
  },
  {
    id: "T-6104",
    agentId: "agent-4",
    agentName: "财务报销 Agent",
    agentIcon: "💰",
    currentNode: "人工确认 · 超额审批",
    progress: 75,
    status: "pending_confirm",
    startedAt: "2026-04-02 13:12",
    duration: "1 小时 8 分钟",
    description: "报销单 #6104 · 培训费 ¥12,800",
  },
  {
    id: "T-2840",
    agentId: "agent-1",
    agentName: "报关 Agent",
    agentIcon: "📦",
    currentNode: "单据审核",
    progress: 25,
    status: "error",
    startedAt: "2026-04-02 14:15",
    duration: "5 分钟",
    description: "报关单 BG-2026-0380 处理",
  },
];

export const MOCK_TASK_EVENTS: Record<string, TaskEvent[]> = {
  "T-2849": [
    {
      id: "ev-1",
      taskId: "T-2849",
      nodeId: "node-1",
      nodeName: "接收委托",
      type: "node_start",
      content: "开始处理报关单 BG-2026-0391",
      timestamp: "2026-04-02 13:57:00",
    },
    {
      id: "ev-2",
      taskId: "T-2849",
      nodeId: "node-1",
      nodeName: "接收委托",
      type: "node_complete",
      content: "委托信息验证通过，货物：电子元器件 x 2000pcs",
      timestamp: "2026-04-02 13:57:30",
    },
    {
      id: "ev-3",
      taskId: "T-2849",
      nodeId: "node-2",
      nodeName: "单据审核",
      type: "node_start",
      content: "开始审核报关单据完整性",
      timestamp: "2026-04-02 13:57:35",
    },
    {
      id: "ev-4",
      taskId: "T-2849",
      nodeId: "node-2",
      nodeName: "单据审核",
      type: "node_complete",
      content: "单据审核通过：发票、装箱单、合同均完整",
      timestamp: "2026-04-02 14:00:00",
    },
    {
      id: "ev-5",
      taskId: "T-2849",
      nodeId: "node-3",
      nodeName: "海关编码归类",
      type: "node_start",
      content: "开始根据商品描述匹配 HS 编码",
      timestamp: "2026-04-02 14:00:05",
    },
    {
      id: "ev-6",
      taskId: "T-2849",
      nodeId: "node-3",
      nodeName: "海关编码归类",
      type: "human_confirm",
      content: "AI 建议编码 8542.31（集成电路），置信度 87%。VIP 客户（华为），请人工确认编码是否正确。",
      timestamp: "2026-04-02 14:05:00",
      details: {
        suggestedCode: "8542.31",
        confidence: 0.87,
        alternativeCodes: ["8542.39", "8541.49"],
      },
    },
  ],
  "T-2848": [
    {
      id: "ev-10",
      taskId: "T-2848",
      nodeId: "node-1",
      nodeName: "合同接收",
      type: "node_complete",
      content: "合同 CT-2026-0178 已接收，金额 ¥580,000",
      timestamp: "2026-04-02 13:32:00",
    },
    {
      id: "ev-11",
      taskId: "T-2848",
      nodeId: "node-2",
      nodeName: "条款解析",
      type: "node_complete",
      content: "已识别 23 个条款，其中 3 个标记为高风险",
      timestamp: "2026-04-02 13:45:00",
    },
    {
      id: "ev-12",
      taskId: "T-2848",
      nodeId: "node-3",
      nodeName: "风险评估",
      type: "human_confirm",
      content: "发现 3 条高风险条款需法务确认：\n1. 违约金条款超出行业标准\n2. 知识产权归属不明确\n3. 交付标准缺少验收细则",
      timestamp: "2026-04-02 14:10:00",
      details: {
        riskLevel: "high",
        riskCount: 3,
      },
    },
  ],
};

export const CONSOLE_STATS = {
  activeAgents: 4,
  monthlyTasks: 517,
  successRate: 96.2,
  pendingItems: 3,
};

// ============================================================
// Skill Market (available skills for Agentic config)
// ============================================================

export interface MarketSkill {
  id: string;
  name: string;
  description: string;
  category: "general" | "industry" | "custom";
  inputs: { name: string; type: string }[];
  outputs: { name: string; type: string }[];
  evaluator?: string;
  callCount: number;
  avgDuration: string;
  status: "available" | "beta" | "deprecated";
}

export const MOCK_MARKET_SKILLS: MarketSkill[] = [
  {
    id: "msk-1",
    name: "网页数据采集",
    description: "从指定 URL 抓取结构化数据，支持动态渲染页面",
    category: "general",
    inputs: [{ name: "URL 列表", type: "string[]" }, { name: "采集规则", type: "json" }],
    outputs: [{ name: "结构化数据", type: "json" }],
    evaluator: "数据完整率 > 95%",
    callCount: 12840,
    avgDuration: "30秒",
    status: "available",
  },
  {
    id: "msk-2",
    name: "文本内容生成",
    description: "根据主题和风格要求生成文本内容（文章/文案/评论等）",
    category: "general",
    inputs: [{ name: "主题", type: "string" }, { name: "风格要求", type: "string" }, { name: "字数范围", type: "string" }],
    outputs: [{ name: "生成内容", type: "string" }, { name: "质量评分", type: "number" }],
    evaluator: "内容原创度 > 90%，可读性评分 > 7",
    callCount: 28350,
    avgDuration: "15秒",
    status: "available",
  },
  {
    id: "msk-3",
    name: "图片生成",
    description: "根据文字描述生成配图，支持多种风格",
    category: "general",
    inputs: [{ name: "描述", type: "string" }, { name: "风格", type: "string" }, { name: "尺寸", type: "string" }],
    outputs: [{ name: "图片 URL", type: "string" }],
    evaluator: "图文相关度 > 80%",
    callCount: 9420,
    avgDuration: "25秒",
    status: "available",
  },
  {
    id: "msk-4",
    name: "数据分析报告",
    description: "对结构化数据进行统计分析并生成可视化报告",
    category: "general",
    inputs: [{ name: "数据集", type: "json" }, { name: "分析维度", type: "string[]" }],
    outputs: [{ name: "分析报告", type: "markdown" }, { name: "图表数据", type: "json" }],
    evaluator: "数据准确率 100%，洞察有效性 > 70%",
    callCount: 5670,
    avgDuration: "45秒",
    status: "available",
  },
  {
    id: "msk-5",
    name: "小红书内容发布",
    description: "自动发布图文内容到小红书平台，支持定时发布",
    category: "industry",
    inputs: [{ name: "标题", type: "string" }, { name: "正文", type: "string" }, { name: "图片", type: "string[]" }, { name: "标签", type: "string[]" }],
    outputs: [{ name: "帖子 ID", type: "string" }, { name: "发布状态", type: "string" }],
    evaluator: "发布成功率 > 99%",
    callCount: 3210,
    avgDuration: "10秒",
    status: "available",
  },
  {
    id: "msk-6",
    name: "竞品数据监控",
    description: "定期采集竞品的公开数据（价格/评价/活动等）",
    category: "industry",
    inputs: [{ name: "竞品列表", type: "json" }, { name: "监控维度", type: "string[]" }],
    outputs: [{ name: "竞品数据", type: "json" }, { name: "变化摘要", type: "string" }],
    evaluator: "数据时效性 < 24h",
    callCount: 1890,
    avgDuration: "2分钟",
    status: "available",
  },
  {
    id: "msk-7",
    name: "合规审查",
    description: "对文本内容进行合规性检查（广告法/平台规则等）",
    category: "industry",
    inputs: [{ name: "待审内容", type: "string" }, { name: "审查规则", type: "string" }],
    outputs: [{ name: "审查结果", type: "json" }, { name: "风险项", type: "json" }],
    evaluator: "漏检率 < 1%",
    callCount: 7650,
    avgDuration: "5秒",
    status: "available",
  },
  {
    id: "msk-8",
    name: "PDF 解析",
    description: "从 PDF 文件中提取结构化文本和表格数据",
    category: "general",
    inputs: [{ name: "PDF 文件", type: "file" }],
    outputs: [{ name: "文本内容", type: "string" }, { name: "表格数据", type: "json" }],
    evaluator: "提取准确率 > 90%",
    callCount: 4320,
    avgDuration: "20秒",
    status: "available",
  },
];
